package main

import (
	"bytes"
	"encoding/json"
	"errors"
	"fmt"
	"io/ioutil"
	"net/http"
	"strconv"
	"time"
)

const (
	LOGIN_API               = "https://api.scaleway.com/account/v2/login"
	ACCOUNT_USERS_API       = "https://api.scaleway.com/account/v2/users/"
	IAM_USERS_API           = "https://api.scaleway.com/iam/v1alpha1/users/"
	SWITCH_ORGANIZATION_API = "https://api.scaleway.com/iam-private/v1/jwts/%s/switch-organization"
	API_KEYS_API            = "https://api.scaleway.com/iam/v1alpha1/api-keys"
	CONTENT_TYPE            = "Content-Type"
	APPLICATION_JSON        = "application/json"
	X_SESSION_TOKEN         = "X-Session-Token"
)

type ScalewayClient struct {
	httpClient            http.Client
	organizationToProfile map[string]OrganizationProfile
	defaultOrganizationId string
	jti                   string
	issuer                string
}

type OrganizationProfile struct {
	jwt    string
	userId string
}

type ApiKey struct {
	AccessKey string `json:"access_key"`
	SecretKey string `json:"secret_key"`
}

type PostBody struct {
	Email    string `json:"email"`
	Password string `json:"password"`
	Token    string `json:"otp"`
}

func NewScalewayClient(email, password, token string) (*ScalewayClient, error) {
	client := ScalewayClient{
		httpClient:            http.Client{},
		organizationToProfile: make(map[string]OrganizationProfile),
	}

	postBody := PostBody{
		Email:    email,
		Password: password,
		Token:    token,
	}
	jsonBody, err := json.Marshal(postBody)
	if err != nil {
		return nil, err
	}

	jsonResponse, err := client.sendRequest(LOGIN_API, jsonBody, "", "POST")
	if err != nil {
		return nil, err
	}

	client.jti = jsonResponse["jwt"].(map[string]interface{})["jti"].(string)
	client.issuer = jsonResponse["jwt"].(map[string]interface{})["issuer_id"].(string)

	client.organizationToProfile[client.defaultOrganizationId] = OrganizationProfile{
		jwt: jsonResponse["token"].(string),
	}

	return &client, nil
}

func (client *ScalewayClient) ListOrganizations() (map[string]string, error) {
	jsonResponse, err := client.sendRequest(IAM_USERS_API+client.issuer, nil, client.getOrCreateOrganizationProfile(client.defaultOrganizationId).jwt, "GET")
	if err != nil {
		return nil, err
	}
	accountRootUserId := jsonResponse["account_root_user_id"].(string)

	jsonResponse, err = client.sendRequest(ACCOUNT_USERS_API+accountRootUserId, nil, client.getOrCreateOrganizationProfile(client.defaultOrganizationId).jwt, "GET")
	if err != nil {
		return nil, err
	}
	orgs := jsonResponse["organizations"].([]interface{})
	result := make(map[string]string)
	for _, org := range orgs {
		orgMap := org.(map[string]interface{})
		result[orgMap["name"].(string)] = orgMap["id"].(string)
	}

	return result, nil
}

func (sc *ScalewayClient) CreateAPIKey(organizationId string, duration time.Duration) (*ApiKey, error) {
	jsonBody, _ := json.Marshal(map[string]string{
		"default_project_id": organizationId,
		"description":        "generated by scw-2fa-init",
		"user_id":            sc.getOrCreateOrganizationProfile(organizationId).userId,
		"expiresAt":          time.Now().Add(duration).UTC().Format(time.RFC3339),
	})

	jsonResponse, err := sc.sendRequest(API_KEYS_API, jsonBody, sc.getOrCreateOrganizationProfile(organizationId).jwt, http.MethodPost)
	if err != nil {
		return nil, err
	}

	accessKey := jsonResponse["access_key"].(string)
	secretKey := jsonResponse["secret_key"].(string)

	return &ApiKey{AccessKey: accessKey, SecretKey: secretKey}, nil
}

func (client *ScalewayClient) getOrCreateOrganizationProfile(organizationId string) OrganizationProfile {
	organizationProfile, ok := client.organizationToProfile[organizationId]
	if !ok {
		jsonBody, _ := json.Marshal(map[string]string{
			"organization_id": organizationId,
		})

		jsonResponse, _ := client.sendRequest(fmt.Sprintf(SWITCH_ORGANIZATION_API, client.jti), jsonBody, client.getOrCreateOrganizationProfile(client.defaultOrganizationId).jwt, "POST")
		organizationProfile = OrganizationProfile{
			jwt:    jsonResponse["token"].(string),
			userId: jsonResponse["user_id"].(string),
		}
		client.organizationToProfile[organizationId] = organizationProfile
	}
	return organizationProfile
}

func (client *ScalewayClient) sendRequest(url string, body []byte, jwt string, method string) (map[string]interface{}, error) {
	req, err := http.NewRequest(method, url, bytes.NewBuffer(body))
	if err != nil {
		return nil, err
	}

	req.Header.Set(CONTENT_TYPE, APPLICATION_JSON)
	if jwt != "" {
		req.Header.Set(X_SESSION_TOKEN, jwt)
	}

	response, err := client.httpClient.Do(req)
	if err != nil {
		return nil, err
	}

	if response.StatusCode >= 400 {
		return nil, errors.New("Request failed with status code: " + strconv.Itoa(response.StatusCode))
	}

	responseBody, _ := ioutil.ReadAll(response.Body)
	var jsonResponse map[string]interface{}
	json.Unmarshal(responseBody, &jsonResponse)

	return jsonResponse, nil
}
