name: Build and Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    permissions:
      contents: write
    name: Build Windows amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v2
        with:
          go-version: 1.20.5
      - run: go get -v -t -d ./...
      - run: GOOS=windows GOARCH=amd64 go build -o downloads/scw-2fa-init-windows-amd64
      - run: GOOS=linux GOARCH=amd64 go build -o downloads/scw-2fa-init-linux-amd64
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          files: downloads/*